# Generated by Django 5.1.4 on 2026-06-08 22:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marketplace', models.CharField(choices=[('OZON', 'Ozon'), ('WB', 'Wildberries')], max_length=10)),
                ('article', models.CharField(help_text='Артикул / SKU товара на маркетплейсе', max_length=64)),
                ('product_url', models.URLField(blank=True, max_length=512)),
                ('title', models.CharField(blank=True, max_length=512)),
                ('current_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
                'constraints': [models.UniqueConstraint(fields=('marketplace', 'article'), name='unique_marketplace_article')],
            },
        ),
        migrations.CreateModel(
            name='PriceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('parsed_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_history', to='tracker.product')),
            ],
            options={
                'verbose_name': 'Запись истории цен',
                'verbose_name_plural': 'История цен',
                'ordering': ['-parsed_at'],
            },
        ),
        migrations.CreateModel(
            name='UserSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_price', models.DecimalField(blank=True, decimal_places=2, help_text='Порог цены. Уведомление придёт, когда цена опустится ниже него.', max_digits=12, null=True)),
                ('notify_on_any_drop', models.BooleanField(default=False, help_text='Уведомлять при любом снижении цены, не только при достижении порога')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='tracker.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Подписка',
                'verbose_name_plural': 'Подписки',
            },
        ),
        migrations.CreateModel(
            name='NotificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('message_preview', models.CharField(blank=True, max_length=256)),
                ('price_history', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notification_logs', to='tracker.pricehistory')),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_logs', to='tracker.usersubscription')),
            ],
            options={
                'verbose_name': 'Лог уведомления',
                'verbose_name_plural': 'Лог уведомлений',
            },
        ),
        migrations.AddIndex(
            model_name='pricehistory',
            index=models.Index(fields=['product', 'parsed_at'], name='idx_price_history_product_time'),
        ),
        migrations.AddConstraint(
            model_name='usersubscription',
            constraint=models.UniqueConstraint(fields=('user', 'product'), name='unique_user_product_subscription'),
        ),
        migrations.AddIndex(
            model_name='notificationlog',
            index=models.Index(fields=['subscription', 'sent_at'], name='idx_notification_log_sub_time'),
        ),
    ]
