# Generated by Django 5.1.4 on 2026-06-09 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_notificationlog_old_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='marketplace',
            field=models.CharField(choices=[('WB', 'Wildberries')], max_length=10),
        ),
    ]
